### PR TITLE
Adjust initialization equation for forward algorithm.

### PR DESCRIPTION
**Pull request by miguelmota**
Should be **`Pi(i)`**`* B(i)(O(0))` instead of `Pi(O(0)) * B(i)(O(0))`

```
𝛼1 𝑖 = 𝜋𝑖𝑏𝑖(𝑜1)
```

http://www.shokhirev.com/nikolai/abc/alg/hmm/hmm.html

### CODE REVIEW

**Comment by ghost** [comment]
:+1:

**Comment by liwenzhu** [comment]
It's great, sorry for reply late, I think it's fixed by #3, if any other problem,  I can reopen this, thanks.

**Comment by ghost** [comment]
@liwenzhu I'm affraid this problem is not related to #3.
In fact, there was a problem with initialization of all three aglorithms - Baum-Welch, Forward and Viterbi.
I think it's necessary to reopen and merge this pull request anyway.

**Comment by ghost** [comment]
Changes in #2 will cause merge conflict, so if you want I can send new pull request with changes made by @miguelmota.

**Comment by liwenzhu** [comment]
@LukaszKrawczyk ok, yes, you are right, I saw it's not the same problem, it's nice if you can send a new pull request, thanks.

**Pull request closed without merging**
